version: '3.8'

services:
  app:
    container_name: realtime-canvas-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["serve", "-s", "dist", "-l", "3000"]
